#!/bin/bash

# Supabase Storage Setup Guide
# Quick reference for setting up the report-images bucket

echo ""
echo "📦 Supabase Storage Setup for CleanMap"
echo "═══════════════════════════════════════════════════════════"
echo ""

BUCKET_NAME="report-images"

echo "Step 1: Create Storage Bucket"
echo "─────────────────────────────"
echo "1. Go to: https://app.supabase.com/project/_/storage/buckets"
echo "2. Click 'New bucket' button"
echo "3. Configure:"
echo "   • Name: $BUCKET_NAME"
echo "   • Public bucket: ✅ YES (check this box!)"
echo "   • File size limit: 5MB (optional)"
echo "   • Allowed MIME types: image/jpeg, image/png, image/webp (optional)"
echo "4. Click 'Create bucket'"
echo ""

echo "Step 2: Configure Storage Policies"
echo "───────────────────────────────────"
echo "1. Go to: https://app.supabase.com/project/_/storage/policies"
echo "2. Select bucket: $BUCKET_NAME"
echo "3. Click 'New policy'"
echo ""
echo "Option A: Use Policy Templates (Easier)"
echo "  • Click 'For full customization create a policy from scratch'"
echo "  • Or use the wizard and select 'Allow public reads' + 'Allow anonymous uploads'"
echo ""
echo "Option B: Use SQL (Advanced)"
echo "  Go to SQL Editor and run:"
echo ""
echo "  -- Allow anonymous uploads (for report submissions)"
echo "  CREATE POLICY \"Allow anonymous uploads\""
echo "  ON storage.objects FOR INSERT"
echo "  TO anon"
echo "  WITH CHECK (bucket_id = '$BUCKET_NAME');"
echo ""
echo "  -- Allow public reads (to view images)"
echo "  CREATE POLICY \"Allow public reads\""
echo "  ON storage.objects FOR SELECT"
echo "  TO anon, authenticated"
echo "  USING (bucket_id = '$BUCKET_NAME');"
echo ""
echo "  -- Optional: Allow authenticated users to delete"
echo "  CREATE POLICY \"Allow authenticated delete\""
echo "  ON storage.objects FOR DELETE"
echo "  TO authenticated"
echo "  USING (bucket_id = '$BUCKET_NAME');"
echo ""

echo "Step 3: Test the Setup"
echo "──────────────────────"
echo "Run the test script:"
echo "  node scripts/test-storage.mjs"
echo ""
echo "Or test via the upload endpoint:"
echo "  curl -X POST http://localhost:3000/api/upload \\"
echo "    -F 'file=@test-image.jpg'"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo ""
echo "⚠️  IMPORTANT:"
echo "  • Make sure 'Public bucket' is enabled (checkbox during creation)"
echo "  • Policies must allow 'anon' role for anonymous uploads"
echo "  • Bucket name must be exactly: $BUCKET_NAME"
echo ""
echo "💡 Common Issues:"
echo "  • 'Bucket not found' → Create the bucket first"
echo "  • 'Policy violation' → Add the storage policies"
echo "  • 'Upload failed' → Check bucket is public and policies are set"
echo ""
